version: "3.9"
services:
  ryu:
#    build: .
    image: "clarkzjw/sabrcontroller:0.1"
    ports:
      - "6633:6633"
      - "8080:8080"
  mongo:
    image: "mongo:5.0"
    ports:
      - "27018:27017"
    volumes:
      - ./mongodb:/data/db
  nginx:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./video:/usr/share/nginx/html
