version: "3.9"
services:
  ryu:
#    build: .
    image: "clarkzjw/sabrcontroller:0.1"
    ports:
      - "6633:6633"
      - "8080:8080"
  mongo:
    image: "mongo:5.0"
    volumes:
      - ./mongodb:/data/db
